[project]
name = "mineria-de-datos-jupyter-notebook"
version = "0.1.0"
description = "Mis proyectos y actividades"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jupyterlab>=4.5.2",
]
